name: lab4d
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - torchvision=0.15.1
  - cudatoolkit-dev=11.7
  - gcc_linux-64=10
  - gxx_linux-64=10
  - matplotlib
  - ninja
  - absl-py 
  - tensorboard 
  - trimesh 
  - scikit-image
  - opencv 
  - einops 
  - numba 
  - gdown 
  - scikit-learn 
  - psutil 
  - av 
  - plotly
  - imageio
  - imageio-ffmpeg
  - tqdm
  - pip:
    - pysdf
    - gradio==3.49.0
    - timm==0.6.7
    - detectron2 @ git+https://github.com/facebookresearch/detectron2.git@e9f7e2b
    - segment_anything @ git+https://github.com/facebookresearch/segment-anything.git
    - groundingdino @ git+https://github.com/IDEA-Research/GroundingDINO.git
    - openmim
    - pyrender
    - open3d==0.17.0
    - geomloss==0.2.6
